name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: | 
        rustup target add x86_64-pc-windows-msvc
        cargo build --verbose --target=x86_64-pc-windows-msvc --release 
    
    - name: Upload assets
      uses: actions/upload-artifact@v3
      with:
        name: intes
        path: target/release/*
          
    - name: Run tests
      run: cargo test --verbose
