name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ
          export SDKROOT=$(pwd)/MacOSX13.3.sdk/
          export PATH=$PATH:~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/
          export CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER=rust-lld
          sudo apt install build-essential cmake mingw-w64 libxft-dev libxmu-dev libxmu-headers libdmx-dev  libxinerama-dev libxfixes-dev libxcursor-dev libxcursor-dev libpango1.0-dev libgtk-3-dev -y
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-apple-darwin
          rustup toolchain install stable-x86_64-pc-windows-gnu
          rustup toolchain install stable-x86_64-unknown-linux-gnu
          rustup toolchain install stable-aarch64-apple-darwin
          cargo build --verbose --target=aarch64-apple-darwin --release
          cargo build --verbose --target=x86_64-unknown-linux-gnu --release
          cargo build --verbose --target=x86_64-pc-windows-gnu --release

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: intes
          compression-level: 0
          path: target/*
